#!/usr/bin/env python3
"""Phase 1f Step 2 (see fabric-port/design/main-compile-plan.md): remove @Override annotations
from methods that only override NeoForge patches to vanilla classes (IItemExtension,
IBlockExtension, IBlockEntityExtension, ...). The method BODIES stay — each one is a NeoForge
hook that must be re-wired (Fabric event, mixin, or documented as dead) in Phases 2-4; every
stripped method is appended to fabric-port/mappings/hook-wiring-checklist.md.

Replayable procedure (after upstream merges too):
    1. .\\gradlew compileJava -PportMain --console=plain -q  >  fabric-port\\census-raw.log 2>&1
    2. python fabric-port/strip_overrides.py fabric-port/census-raw.log
    3. recompile; the "method does not override" cluster must be gone
Only lines that actually read `@Override` are touched; anything unexpected is reported and
skipped. Commit the rewrites as [scripted].
"""
import io
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CHECKLIST = REPO / 'fabric-port' / 'mappings' / 'hook-wiring-checklist.md'
ERR = re.compile(r'^(.*?\.java):(\d+): error: method does not override or implement a method from a supertype')
METHOD_NAME = re.compile(r'(?:^|\s)(\w+)\s*\(')


def main(log_path: str) -> int:
    targets = defaultdict(list)  # file -> [line numbers, 1-based]
    for raw in io.open(log_path, encoding='utf-8', errors='replace'):
        m = ERR.match(raw.strip())
        if m:
            targets[m.group(1)].append(int(m.group(2)))
    if not targets:
        print('no "method does not override" errors found in log')
        return 0

    stripped = []  # (relative file, method name)
    skipped = 0
    for file, line_nos in sorted(targets.items()):
        path = Path(file)
        text = io.open(path, encoding='utf-8').read()
        lines = text.splitlines(keepends=True)
        for ln in sorted(set(line_nos), reverse=True):  # bottom-up keeps numbers valid
            idx = ln - 1
            if idx >= len(lines):
                print(f'SKIP {file}:{ln}: line out of range')
                skipped += 1
                continue
            content = lines[idx]
            if content.strip() == '@Override':
                del lines[idx]
                method_line = next((l for l in lines[idx:idx + 6] if '(' in l), '')
            elif content.lstrip().startswith('@Override'):
                # annotation shares the line with the declaration
                lines[idx] = content.replace('@Override', '', 1)
                method_line = content
            else:
                print(f'SKIP {file}:{ln}: expected @Override, found: {content.strip()[:60]}')
                skipped += 1
                continue
            name = METHOD_NAME.search(method_line)
            rel = path.as_posix().split('src/main/java/')[-1]
            stripped.append((rel, name.group(1) if name else '?'))
        io.open(path, 'w', encoding='utf-8', newline='').write(''.join(lines))

    # merge into the wiring checklist (sorted, unique, existing check state preserved)
    existing = ''
    if CHECKLIST.exists():
        existing = io.open(CHECKLIST, encoding='utf-8').read()
    else:
        existing = ('# NeoForge hook-wiring checklist (generated by strip_overrides.py)\n\n'
                    'Every method below lost its @Override because the overridden method only exists in\n'
                    "NeoForge's vanilla patches — so NOTHING CALLS IT on Fabric until it is re-wired.\n"
                    'Resolve each entry in Phases 2-4: wire via Fabric API event/hook, a mixin, or mark\n'
                    'dead-on-Fabric with a reason. Do not delete entries; check them off with the fix.\n\n')
    added = 0
    for rel, name in sorted(set(stripped)):
        entry = f'- [ ] `{rel}` — `{name}`'
        if entry not in existing:
            existing += entry + '\n'
            added += 1
    CHECKLIST.parent.mkdir(parents=True, exist_ok=True)
    io.open(CHECKLIST, 'w', encoding='utf-8', newline='\n').write(existing)

    print(f'stripped {len(stripped)} @Override annotations in {len(targets)} files; '
          f'{skipped} skipped; {added} new checklist entries -> {CHECKLIST.relative_to(REPO)}')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else 'fabric-port/census-raw.log'))
